<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <AssemblyName>MilkVio.ACR</AssemblyName>
    <RootNamespace>MilkVio</RootNamespace>

    <!-- NuGet SDK 中的 DLL 只用于编译，不复制到 ACR 输出目录 -->
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>

    <!-- 本地编译时直接部署到繁中服 ACR 目录 -->
    <OutputPath>$(APPDATA)\XIVLauncherTC\pluginConfigs\PromeRotation\ACR\MilkVio\</OutputPath>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PromeRotation.SDK.TC"
                      Version="0.1.0-preview.1" />
  </ItemGroup>

</Project>